version: "3.8"
networks:
  hasura:
    name: hasura
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8082:8080"
    restart: always
    networks:
      - hasura
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:123456aA@postgres:5432
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "zUIw0txj8ng0"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"d37F5rCwlGNicoZ1W6uDDfzgr5UnWmMB"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "ANONYMOUS"
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    networks:
      - hasura
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456aA
